name: pytorch-tutorials
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy>=1.22.0,<2
  - pandas>=1.4.2
  - scikit-learn>=1.0.2
  - scipy>=1.7.3
  - seaborn>=0.11
  - pytorch>=1.9.0
  - torchvision
  - torchaudio
  - ipykernel
  - jupyterlab
  - pip
  - pip:
      - hydra-core
      - lightning
      - igraph
      - transformers
      - timm
